### ISSUE TITLE
[ENHANCEMENT] Add Northbound traffic support for ANP API

### ISSUE THREAD

**Issue by tssurya** [kubernetes-sigs/network-policy-api#126]
**Is your enhancement request related to a problem? Please describe.**
This is follow of up of https://github.com/kubernetes-sigs/network-policy-api/issues/28
This issue tracks adding support for northbound traffic use case and also host-networked pod traffic use case for ANP from CNI pods.

**Describe the solution you'd like**
https://github.com/kubernetes-sigs/network-policy-api/pull/117 outlines the details, it has undergone some rounds of review already at https://github.com/kubernetes-sigs/network-policy-api/pull/86 

**Describe alternatives you've considered**

**Additional context**

```[tasklist]
### Tasks
- [ ] https://github.com/kubernetes-sigs/network-policy-api/pull/117
- [ ] https://github.com/kubernetes-sigs/network-policy-api/pull/143
- [ ] Document egress samples
- [ ] https://github.com/kubernetes-sigs/network-policy-api/pull/144
- [ ] https://github.com/kubernetes-sigs/network-policy-api/pull/185
- [ ] https://github.com/kubernetes-sigs/network-policy-api/pull/193
```

**Comment by tssurya** [comment]
Now that the Provisional NPEP is done, I am working on PoC to implement it and then will re-open the NPEP in the implementable phase with link to PoC.

**Comment by tssurya** [comment]
Status:

1. All design phase NPEPs have merged
2. NodeSelector peer API change has merged
3. inline CIDR selector API change PR is under progress
4. Starting on conformance tests for nodeselector

**Comment by tssurya** [comment]
Status:

1. All design phase NPEPs have merged
2. NodeSelector peer API change has merged
3. inline CIDR selector API change PR is merged
4. nodeSelector conformance test PR is waiting for reviews
5. starting on cidr conformance tests

**Comment by tssurya** [comment]
This task is done, closing it!
