### ISSUE TITLE
[ENHANCEMENT] Conformance Profiles: An easy way for implementations to report conformance tests results

### ISSUE THREAD

**Issue by tssurya** [kubernetes-sigs/network-policy-api#137]
**Is your enhancement request related to a problem? Please describe.**
This issue aims to track the conformance profiles effort around network-policy-api. Adapted with love from https://github.com/kubernetes-sigs/gateway-api/blob/main/geps/gep-1709.md

**Describe the solution you'd like**
We already have conformance tests for ANP&BANP API - basics being done already and we have two implementations OVNK and Antrea which have adopted this downstream in their repos and are running it there. I'd like to take this one step further and add support for Conformance Profiles which will help report the results of these tests back upstream that will let implementations get the "conformance" badges..

**Describe alternatives you've considered**
Alternatives are for us to start running implementation specific e2e's in net-pol-api repo here which is not recommended. This NPEP will help share the responsibility of maintaining the test suites to the implementors and the API designers

**Additional context**
Output will look like this: https://github.com/kubernetes-sigs/gateway-api/pull/1967#pullrequestreview-1408166850 NOTE: Unlike GatewayAPI we don't have any experimental channels, so this NPEP is just going to be straight up "Implementable" status. NetPol project is going to adopt this reporting mechanism as a way the forward.

```[tasklist]
### Tasks
- [x] Create NPEP for conformance profiles: https://github.com/kubernetes-sigs/network-policy-api/pull/138
- [x] Implement conformance profiles: https://github.com/kubernetes-sigs/network-policy-api/pull/142
- [x] Create repo to maintain reports of results from implementations: https://github.com/kubernetes-sigs/network-policy-api/pull/142
- [ ] Document Conformance Profiles for implemenations
```

**Comment by tssurya** [comment]
/remove-lifecycle stale
This work is done now, all cards are merged already.
Only thing remaining was docs part which @astoycos already did when he made the NPEP part of the website
