### ISSUE TITLE
DOCUMENTATION

### ISSUE THREAD

**Issue by astoycos** [kubernetes-sigs/network-policy-api#36]
We need to have a ton of documentation for the new AdminNetworkPolicy API 

I've started putting together a website in #33 but there is still much more to do, we need specifically 

- More Yaml examples of AdminNetworkPolicies and BaselineAdminNetworkPolicies
- Update the [KEP](https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/2091-admin-network-policy) to reflect the design changes that occurred during API review 
- Spruce up this repo's readme explaining what it contains and it's relevance  

```[tasklist]
### Tasks
- [x] More Yaml examples of AdminNetworkPolicies and BaselineAdminNetworkPolicies
- [x] Update the [KEP](https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/2091-admin-network-policy) to reflect the design changes that occurred during API review  -> https://github.com/kubernetes/enhancements/pull/3660
- [x] Spruce up this repo's readme explaining what it contains and it's relevance
- [x] Move AdminNetworkPolicy info into it's own subdomain -> #91
- [ ] Add more sample yaml's for AdminNetworkPolicy
```

**Comment by zahertalab** [comment]
Is it a RESTful API?

**Comment by astoycos** [comment]
@zahertalab It's a CRD for the Kubernetes API which is RESTful :)
